window.quotes = [
    {author: 'Oscar', text: 'Learning is difficult, but I am not giving up!'},
    {author: 'Theodore Roosevelt', text: 'Believe you can and you\'re halfway there.'},
    {author: 'Helen Keller', text: 'The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart'},
    {author: 'Mark Twain', text: 'All you need in this life is ignorance and confidence; then success is sure'},
    {author: 'Franklin D. Roosevelt', text: 'The only thing we have to fear is fear itself'},
    {author: 'Martin Luther King', text: 'I have a dream'},
    {author: 'Oscar Wilde', text: 'Be yourself; everyone else is already taken.'},
    {author: 'Frank Zappa', text: 'So many books, so little time'},
    {author: 'Marcus Tullius Cicero', text: 'A room without books is like a body without a soul.'},
    {author: 'Bernard M. Baruch', text: 'Be who you are and say what you feel, because those who mind don\'t matter, and those who matter don\'t mind.'},
    {author: 'Mae West', text: 'You only live once, but if you do it right, once is enough.'},
    {author: 'Robert Frost', text: 'In three words I can sum up everything I\'ve learned about life: it goes on.'},
    {author: 'Mark Twain', text: 'If you tell the truth, you don\'t have to remember anything.'},
    {author: 'Oscar Wilde', text: 'To live is the rarest thing in the world. Most people exist, that is all.'},
    {author: 'C.S. Lewis, The Four Loves', text: 'Friendship ... is born at the moment when one man says to another "What! You too? I thought that no one but myself . . .'},
    {author: 'Elbert Hubbart', text: 'A friend is someone who knows all about you and still loves you.'},
    {author: 'Mahatma Gandhi', text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.'},
    {author: 'Friedrich Nietzsche, Twilight of the Idols', text: 'Without music, life would be a mistake.'},
    {author: 'Oscar Wilde, The Happy Prince and Other Stories', text: 'I am so clever that sometimes I don\'t understand a single word of what I am saying.'},
    {author: 'Ralph Waldo Emerson', text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.'},
    {author: 'Narcotics Anonymous', text: 'Insanity is doing the same thing, over and over again, but expecting different results.'},
    {author: 'Andre Gide, Autumn Leaves', text: 'It is better to be hated for what you are than to be loved for what you are not.'},
    {author: 'René Descartes', text: 'I think, therefore I am'}
]